### ISSUE TITLE
Multiple users interacting with sheet cause loss of work

### ISSUE THREAD

**Issue by PhyDoesStuff** [StasTserk/foundry-burningwheel#152] opened 2020-09-23 01:39 UTC
**Describe the bug**
In cases where 2+ users are interacting with a sheet, certain interactions with the sheet (create/remove/edit objects in the sheet, open/close sheet) will interrupt work on Items (trait, item, spell, skill, relationship, reputation) within the sheet, reverting the contents of the Item to an earlier point.

**To Reproduce**
The steps below specify creating a trait, but the behavior can be replicated with items, spells, skills, relationships, and reputations. Basically, anything that you can add to the sheet with a "+" or "+ Add New X" button.
1. User 1 creates new trait, "test", in Character
2. User 1 begins editing "test"
3. User 2 opens Character's sheet
4. Any modifications to details of "test" are lost

1. User 1 and User 2 open Character's sheet
2. User 1 creates new trait, "test", in Character
3. User 1 begins editing "test"
4. User 2 closes Character's sheet, or creates/edits/deletes an Item on Character's sheet
5. Any modifications to details of "test" are lost

**Expected behavior**
At the very least, another user opening or closing a sheet should not revert the Item being worked on. Instead of having live saving, maybe an edit/save process would work better? That way, the Item can be worked on independent of the rest of the sheet's contents, then saved, which would update the sheet's contents appropriately.

**Comment by StasTserk** [comment] 2020-09-23 01:52
This sounds like an issue with the way Foundry handles data persistence. I'll look in to see if there's anything I can do to alleviate this, but there's a chance that fixing this will involve some particularly onerous overrides of Foundry's behaviour in which case this might end up as a `won't fix` and a reported issue to the foundry repo.

**Comment by StasTserk** [comment] 2020-10-06 07:37
Did a bit of digging around, it appears as though closing a sheet will have foundry trigger a submission of the form (I imagine to make sure that even if you close the sheet while editing text it is persisted.)

This form submission triggers a database update even if no data has changed which is propagated to every client, triggering a render of the form.

I'm going to need to do a bit more digging to make sure this isn't something that's happening due to something I did, but more than likely it's an issue with foundry which would need to be addressed there -- trying to patch this locally is not something that would be ideal given the relatively minor issue and fragility it would introduce into the code.

**Comment by StasTserk** [comment] 2020-10-12 21:33
So, final round of investigation, I believe I have a pretty solid grasp of the issues involved. In general lost work is due to a sheet's render being called on a client by something another client is doing. Render is triggered in a number of ways, but primarily this is due to foundry detecting a data change and persisting that data in the database and propagating that change to all connected clients.

A number of issues are at work here which result in undesired render calls.
1. Closing a sheet triggers an update which persists data even though no data has changed. This happens because a character's sheet has a number of radio controls which track progress for skills which show up in the form data object, but are not bound to an actor's data. Normally, submitting a sheet with no data changed is caught by diffing the actor's data with the form data object. If no changes are detected, the process ends there and no database call or render call is made. However, the radio inputs appear in form data and never in the actor's data. This causes foundry to attempt to save them every time, triggering an update and render for the form. **This isn't something that can be fixed until foundry adds proper support for radio button inputs.**
2. Adding a new item triggers a render on an open item sheet. This is unfortunately expected behavior in foundry. When a new item is added foundry actually triggers a render on the actor sheet to which the item is added *as well as* [every item sheet associated with the actor](https://foundryvtt.com/api/foundry.js.html#line9396). This is behavior that is explicitly defined in the core of foundry and as such is rather out of my hands.

As it is, while unfortunate, it is currently not something that can be addressed due to being an outcome of the way foundry handles data persistence and synchronization at a low level. Future versions of foundry will hopefully address some of the root causes of this. For now, closing this issue as `wont fix`

**Closed** 2020-10-12 21:34 UTC
Labels: bug, wontfix
